### PR TITLE
Fix for relnotes link to match 14.2 release version.

### PR DESCRIPTION
**Pull request by epu**
* Addresses github issue #1

### CODE REVIEW

**Comment by caskater4** [comment]
The package has been updated for the 2014.3 release so this patch while appreciated is no longer necessary.

**Comment by epu** [comment]
Should the p4 package remain at 2014.2?
There isn’t a p4 server release at 2014.3 that I can find (although there is a p4v at 2014.3, which I was going to update..)

**Comment by caskater4** [comment]
The p4 package was updated to 2015.1 as is the latest available from Perforce’s website.

**Comment by epu** [comment]
Ah, perfect, thanks.

Is there someone on the chocolatey team I shoud bump/nag to speed up moderation?

-e

**Comment by caskater4** [comment]
Unfortunately there’s no direct e-mail I could give you for bugging. Based on past experience they should approve it by tomorrow sometime.

**Comment by epu** [comment]
Oh, that’s not bad at all.
Thanks for updating everything!
-e

**Pull request closed without merging**
